name: End-to-End Tests with Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Iniciar ambiente Docker
        run: |
          cd Ambiente
          docker compose up --build -d
          sleep 200
          docker compose ps

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Verificar ambiente
        run: |
          cd Ambiente
          sleep 60
          docker compose ps

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v5

      - name: Encerrar ambiente Docker
        if: always()
        run: |
          cd Ambiente
          docker compose down
